### ISSUE TITLE
Document hostname.domainname minion-name is req.

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/deepsea-formula#6]
Need to document requirement for `hostname.domainname` minion name format
```
root@onion:~# salt-run state.orch ceph.stage.1
salt-api                 : valid
deepsea_minions          : valid
master_minion            : valid
ceph_version             : valid
salt_version             : valid
[WARNING ] All minions are ready
[ERROR   ] Exception occurred in runner populate.proposals: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 382, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/modules/runners/populate.py", line 911, in proposals
    ceph_roles.cluster_config()
  File "/srv/modules/runners/populate.py", line 615, in cluster_config
    contents['fsid'] = str(uuid.uuid3(uuid.NAMESPACE_DNS, random_string))
  File "/usr/lib/python2.7/uuid.py", line 579, in uuid3
    hash = md5(namespace.bytes + name).digest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa7 in position 1: ordinal not in range(128)

{}
onion_master:
  Name: minions.ready - Function: salt.runner - Result: Changed Started: - 16:11:40.662088 Duration: 1655.765 ms
  Name: refresh_pillar0 - Function: salt.state - Result: Changed Started: - 16:11:42.318162 Duration: 845.39 ms
----------
          ID: discover roles
    Function: salt.runner
        Name: populate.proposals
      Result: False
     Comment: Exception occurred in runner populate.proposals: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 382, in _low
                  data['return'] = self.functions[fun](*args, **kwargs)
                File "/srv/modules/runners/populate.py", line 911, in proposals
                  ceph_roles.cluster_config()
                File "/srv/modules/runners/populate.py", line 615, in cluster_config
                  contents['fsid'] = str(uuid.uuid3(uuid.NAMESPACE_DNS, random_string))
                File "/usr/lib/python2.7/uuid.py", line 579, in uuid3
                  hash = md5(namespace.bytes + name).digest()
              UnicodeDecodeError: 'ascii' codec can't decode byte 0xa7 in position 1: ordinal not in range(128)
     Started: 16:11:43.164503
    Duration: 7765.134 ms
     Changes:   
  Name: proposal.populate - Function: salt.runner - Result: Changed Started: - 16:11:50.930001 Duration: 5985.242 ms

Summary for onion_master
------------
Succeeded: 3 (changed=3)
Failed:    1
------------
Total states run:     4
Total run time:  16.252 s
```

**Comment by noelmcloughlin** [comment]
Fixes above issue:
```
root@onion:~# salt-run state.orch ceph.stage.1
salt-api                 : valid
[WARNING ] VALIDATE ceph_version: No Ceph version is available for installation on minion onion
[WARNING ] All minions are ready
[ERROR   ] Exception occurred in runner populate.proposals: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 382, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/modules/runners/populate.py", line 909, in proposals
    ceph_roles = CephRoles(settings, name, ceph_cluster.minions, salt_writer)
  File "/srv/modules/runners/populate.py", line 497, in __init__
    self.networks = self._networks(self.servers)
  File "/srv/modules/runners/populate.py", line 639, in _networks
    for nic in interfaces[minion]:
TypeError: 'bool' object is not iterable

[ERROR   ] Exception occurred in runner proposal.populate: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 382, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/srv/modules/runners/proposal.py", line 335, in populate
    _proposal = _choose_proposal(node, proposal, args)
  File "/srv/modules/runners/proposal.py", line 205, in _choose_proposal
    if conf in proposal:
TypeError: argument of type 'bool' is not iterable

onion.example.com_master:
  Name: minions.ready - Function: salt.runner - Result: Changed Started: - 16:25:17.344118 Duration: 16728.489 ms
  Name: refresh_pillar0 - Function: salt.state - Result: Changed Started: - 16:25:34.072987 Duration: 2075.307 ms
----------
          ID: discover roles
    Function: salt.runner
        Name: populate.proposals
      Result: False
     Comment: Exception occurred in runner populate.proposals: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 382, in _low
                  data['return'] = self.functions[fun](*args, **kwargs)
                File "/srv/modules/runners/populate.py", line 909, in proposals
                  ceph_roles = CephRoles(settings, name, ceph_cluster.minions, salt_writer)
                File "/srv/modules/runners/populate.py", line 497, in __init__
                  self.networks = self._networks(self.servers)
                File "/srv/modules/runners/populate.py", line 639, in _networks
                  for nic in interfaces[minion]:
              TypeError: 'bool' object is not iterable
     Started: 16:25:36.149371
    Duration: 139418.097 ms
     Changes:   
----------
          ID: discover storage profiles
    Function: salt.runner
        Name: proposal.populate
      Result: False
     Comment: Exception occurred in runner proposal.populate: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/client/mixins.py", line 382, in _low
                  data['return'] = self.functions[fun](*args, **kwargs)
                File "/srv/modules/runners/proposal.py", line 335, in populate
                  _proposal = _choose_proposal(node, proposal, args)
                File "/srv/modules/runners/proposal.py", line 205, in _choose_proposal
                  if conf in proposal:
              TypeError: argument of type 'bool' is not iterable
     Started: 16:27:55.567932
    Duration: 62541.603 ms
     Changes:   

Summary for onion.example.com_master
------------
Succeeded: 2 (changed=2)
Failed:    2
------------
Total states run:     4
Total run time: 220.763 s
```

**Comment by noelmcloughlin** [comment]
Won't fix.
